I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Character.rpy", line 77, in script call
    call screen talk_menu_screen
  File "game/Alinor.rpy", line 12, in script
    j_smile "Сейчас мне незачем возвращаться."
Exception: Sayer 'j_smile' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Character.rpy", line 77, in script call
    call screen talk_menu_screen
  File "game/Alinor.rpy", line 12, in script
    j_smile "Сейчас мне незачем возвращаться."
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 615, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 528, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'j_smile' is not defined.

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
 
Sun Mar 01 09:26:29 2020
