I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Alinor.rpy", line 25, in script call
    $ location("Alinor", "trading_area", "alinor_stolica")
  File "game/System.rpy", line 423, in script
    show expression show_random_button1
TypeError: argument of type 'int' is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Alinor.rpy", line 25, in script call
    $ location("Alinor", "trading_area", "alinor_stolica")
  File "game/System.rpy", line 423, in script
    show expression show_random_button1
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 1110, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\ast.py", line 1069, in show_imspec
    expression = renpy.easy.displayable(expression)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\easy.py", line 99, in displayable
    return renpy.display.image.DynamicImage(d, scope=scope)
  File "D:\Programms\Renpy\renpy-6.99.14.1-sdk\renpy\display\image.py", line 486, in __init__
    if ("[prefix_" in i):
TypeError: argument of type 'int' is not iterable

Windows-7-6.1.7601-SP1
Ren'Py 6.99.14.1.3218
 
Thu Dec 27 19:47:56 2018
