I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/System.rpy", line 10, in script
    image vorota dvorca = "Images/Alinor/vorota1.jpg",
Exception: Not a displayable: (u'Images/Alinor/vorota1.jpg',)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/System.rpy", line 10, in script
    image vorota dvorca = "Images/Alinor/vorota1.jpg",
  File "D:\JKTVR18\Krjutskova\Renpy\renpy-7.1.1-sdk\renpy\ast.py", line 985, in execute
    renpy.exports.image(self.imgname, img)
  File "D:\JKTVR18\Krjutskova\Renpy\renpy-7.1.1-sdk\renpy\exports.py", line 366, in image
    d = renpy.easy.displayable(d)
  File "D:\JKTVR18\Krjutskova\Renpy\renpy-7.1.1-sdk\renpy\easy.py", line 136, in displayable
    raise Exception("Not a displayable: %r" % (d,))
Exception: Not a displayable: (u'Images/Alinor/vorota1.jpg',)

Windows-8-6.2.9200
Ren'Py 7.1.1.929
 
Mon Nov 12 13:09:38 2018
